### ISSUE TITLE
A found vulnerability results in "throw new Error(message)"

### ISSUE THREAD

**Issue by alertme-edwin** [jeemok/better-npm-audit#19]
Thanks for this excellent npm package.  I was slightly surprised, though, that when a vulnerability is found by the audit, the output includes 20 lines more than the usual `npm audit`, including a stacktrace and `npm` denying all responsibility with its `This is probably not a problem with npm.` message.

There are times when throwing exceptions is the right way to control code flow, but the user experience here doesn't seem to be better than that of the original `npm audit` feature, which exits more cleanly.  Also, if an audit tool correctly discovers that there are vulnerabilities in a project then arguably that should be treated as a success, although I understand that the purpose of this check is often to prevent a build pipeline from continuing, so it makes sense to provide an exit status which reflects that.

Hopefully you don't mind if I make an additional unimportant observation here, which is that line 11 of `/index.js` is missing a semicolon, unlike the lines around it.  Perhaps you would consider including some sort of linting step to accompany your impressive testing procedure.

**Comment by jeemok** [comment]
Thanks for the feedback! I think that's a good suggestion, I was thinking of adding Eslint into this project for a long time but didn't really do it until now. I will look into exits strategy later. PRs are welcome if you'd like to contribute too :)
