### ISSUE TITLE
execution is breaking when stdout returns a string with first character as number

### ISSUE THREAD

**Issue by samarthmaniar** [jeemok/better-npm-audit#2]
I observed this today while running better-npm-audit, while reading stdout for `npm audit` command in index.js, if ids are set to something like "0m│http,npmj,1012,http,npmj,1012,http,npmj,1012", then it breaks the execution as following code in index.js returns "[ '0m│\u001b' ]"

`const numberIds = ids.map(id => {
        if (isNaN(parseInt(id, 10))) {
          return null;
        }
        return id;
      }).filter(Boolean);`

**Comment by jeemok** [comment]
Thanks for the report! I've published a patch for this. Please install version `0.1.7` for the updates.
Closing this issue now, please let me know if you have any question.

Cheers,
Mok
