### ISSUE TITLE
IDs on the exception list missing from "audit" output

### ISSUE THREAD

**Issue by alertme-edwin** [jeemok/better-npm-audit#23]
Thanks for the great version 1.9.1 update.  I've installed it and run the audit again, but there seems to have been a small regression with the output.  Here is a section from the audit report:

```
> node node_modules/better-npm-audit audit

Exception vulnerabilities ID(s): 
                                                                                
                       === npm audit security report ===
```

My guess is that `consoleUtil` on line 135:

`consoleUtil.info('Exception vulnerabilities ID(s): ', exceptionIds);`

does not work the way `console` did.

**Comment by jeemok** [comment]
you're right! sorry for the mistake, will release a patch version soon

**Comment by alertme-edwin** [comment]
I can confirm the patch works.  Thanks for the new version!
