### ISSUE TITLE
Missing [ in truncation message

### ISSUE THREAD

**Issue by alertme-edwin** [jeemok/better-npm-audit#28]
Just another small issue while I'm reporting things.  I get output like this:

```
...
├───────────────┼──────────────────────────────────────────────────────────────┤



MAXIMUM EXCEEDED] Logs exceeded the maximum length limit. Add the flag `-f` to see the full audit logs.
...
```

From the code, it looks like there should be a `[` at the start of the line, which would look nicer.  I'm not sure what is swallowing that.

**Comment by jeemok** [comment]
hmm I couldn't reproduce this on my side, do you mind sharing more information? like the version, or more of the logs output (I can't see the triple dots `...` above the `MAXIMUM EXCEEDED` line too)

**Comment by alertme-edwin** [comment]
Sure, thanks for looking at this.

I'm running npm `6.14.4` and better-npm-audit `1.9.2`.  The first `...` is what I used to represent the backscroll, containing the ASCII-art tables of vulnerability details, and the last `...` represents the remaining few lines of the output, i.e. white space and the `🤝  All good!` message.

**Comment by jeemok** [comment]
it looks weird to me as it should have triple dots `...` above the warning message, e.g.:

```
...
├───────────────┼──────────────────────────────────────────────────────────────┤

... // <--- this seems missing

MAXIMUM EXCEEDED] Logs exceeded the maximum length limit. Add the flag `-f` to see the full audit logs.
...
```

and I couldn't reproduce it on my side running with `1.9.2`. Anyway, I think coming very soon we might improve the library performance and output rendering by creating the ASCII table ourselves, and this could be handled more gently too. I will post more updates in this issue if I managed to gather more data

**Comment by alertme-edwin** [comment]
Just to confirm, I am still seeing this with version `1.10.1`.  Here is another example of a section from near the end of the audit output:

```
│ Path          │ REDACTED                                           > cssnano │
│               │ > cssnano-preset-default > postcss-discard-overridden >      │



MAXIMUM EXCEEDED] Logs exceeded the maximum length limit. Add the flag `-f` to see the full audit logs.


9 vulnerabilities found. Node security advisories: REDACTED,REDACTED,REDACTED
npm ERR! code ELIFECYCLE
```

(Again I've redacted some of the specific details of the vulnerabilities that I used in this test set up, to not draw too much focus to individual packages).

Don't worry if you can't reproduce this on your machine.  I look forward to seeing any update to the output rendering, and will test this issue again when any relevant change is released.

**Comment by alertme-edwin** [comment]
I've been looking into this more, and I think I have a better understanding of it.  Firstly, I see what you mean about expecting "`...`" in the output (and I can confirm I don't see it).  More importantly, though, I think the problem might be related to a bug in NodeJS itself (there have been various issues filed, but one that is still open is #6379), and there is potentially a workaround.

Have a look at [pyright pull request 1905](https://github.com/microsoft/pyright/pull/1905) for a discussion about truncated CLI output, and a code change which shows how they avoided `process.exit()` (to follow the recommendation of the NodeJS docs, apparently).

**Comment by jeemok** [comment]
I see... hmm this is interesting. However, I think this could be solved together when we implemented our own display method, I was researching about NPM v6 and v7 audit report format and thinking which one should I be using (or none of them). I will try to work on it this weekend (hope I have enough time 🤞🏻)
