### ISSUE TITLE
Node version 14.17.0 is not supported

### ISSUE THREAD

**Issue by guillermaster** [jeemok/better-npm-audit#30]
The `better-npm-audit `does not work with the most recent Nodejs version. I am using version  14.17.0 and it throws an exception. I think it is because this version of Node has a breaking change in the way the `npm audit` command returns the results.

Below is the error message from the exception.

`const vulnerabilities = Object.values(advisories)`
                                   ^

```
TypeError: Cannot convert undefined or null to object
    at Function.values (<anonymous>)
    at Socket.<anonymous> (/Users/guillermo.pincay/Documents/bamboo-plus-api/node_modules/better-npm-audit/index.js:103:36)
    at Socket.emit (events.js:388:22)
    at Pipe.<anonymous> (net.js:673:12)
```

**Comment by jeemok** [comment]
hey @guillermaster ! 👋🏻  thanks for reporting it! hmm, I couldn't locate that line of code, may I know which version of this library are you using?

**Comment by guillermaster** [comment]
Hi @jeemok. I'm using version 1.3.1. It works well with environments using Node version 14.11.0 but not on those using 14.17.0.

**Comment by jeemok** [comment]
I couldn't find anything in the [v14 changelog](https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V14.md) mentioning changes on the audit command. I think this is related to these issue/PR

- https://github.com/jeemok/better-npm-audit/issues/13
- https://github.com/jeemok/better-npm-audit/pull/12

and has been fixed in the newer versions, can you please try with `v1.9.2`?

**Comment by guillermaster** [comment]
@jeemok you are right. The issue has been fixed on the version 1.9.2. Thank you!

PS: It'd be good to have a changelog in the repository 😉

**Comment by guillermaster** [comment]
This is a duplicated issue. The author, @jeemok , has already solved the issue in the latest version.

**Comment by jeemok** [comment]
yeah, I think that's a good practice, will definitely keep that in mind for newer releases!
