### ISSUE TITLE
Support level being passed in as an environment variable

### ISSUE THREAD

**Issue by jmac105** [jeemok/better-npm-audit#35]
Hi,

I'd find it really useful if the level option could be passed in as an environment variable, as it can be to the native `npm audit` command via `NPM_CONFIG_AUDIT_LEVEL` environment variable. This would allow for setting a global audit level across all of our CI pipeline builds, some of which use 'npm audit' and some of which use 'better-npm-audit audit'. 

Would you consider a PR which would set a default value for level as a fourth parameter here https://github.com/jeemok/better-npm-audit/blob/7ad4a72d113f54d440449d7bb2bc2bcdbddb1110/index.js#L173, taking the value from `process.env.NPM_CONFIG_AUDIT_LEVEL`? 

Cheers

**Comment by jeemok** [comment]
yeah I think that is a good idea, let me prepare the PR now

**Comment by jeemok** [comment]
@jmac105 you can now install and use it in `v1.11.0`. Thanks for the suggestion! :)

**Comment by jmac105** [comment]
Awesome thanks for actioning it so quickly!
