### ISSUE TITLE
Process keeps hanging on Windows 10

### ISSUE THREAD

**Issue by Pouja** [jeemok/better-npm-audit#62]
The process keeps hanging in a happy flow (when there are no issues reported). I think this is because the buffer doesn't close properly on Windows due to not properly listing to the kill signal of the child process.

This can be fixed by adding `process.exit(0)` after https://github.com/jeemok/better-npm-audit/blob/master/src/handlers/handleFinish.ts#L49

**Comment by jeemok** [comment]
Thanks for reporting @Pouja ! I've released a [new version](https://www.npmjs.com/package/better-npm-audit/v/3.5.1) and it should be fixed now
