### ISSUE TITLE
Using --full doesn't print the raw logs when an error is encountered

### ISSUE THREAD

**Issue by Deiiv** [jeemok/better-npm-audit#8]
The flag --full, described as "Display full report", only prints the full report when no vulnerability is found. However, this flag should print the full report in both cases.

Normal usage without --full (-f):

Command: `node node_modules/better-npm-audit audit`

![image](https://user-images.githubusercontent.com/24512337/87048198-6ed10200-c1c9-11ea-962b-289c7d14e727.png)

Using --full (-f):

Command: `node node_modules/better-npm-audit audit -f`

![image](https://user-images.githubusercontent.com/24512337/87048240-7bedf100-c1c9-11ea-946f-8a2e79329f37.png)

Adding -i to ignore the vulnerability (and hence get a "success" response):

Command: `node node_modules/better-npm-audit audit -f -i 1523`

![image](https://user-images.githubusercontent.com/24512337/87047919-1bf74a80-c1c9-11ea-8e14-fbeb3985888c.png)

The reason this isn't happening is because of the following code section:

https://github.com/jeemok/better-npm-audit/blob/fc42a2baa5765f269c5ae0dbbfd7ccd0046287b1/index.js#L107-L113

It can be fixed by taking the auditLog() call outside of the if condition.

**Comment by jeemok** [comment]
Hi @Deiiv, sorry for the late response. The `-f` full flag is meant for security reports that are way too long (that could probably take up to 5 minutes to render in your terminal on your screen, hence we limit it to a maximum length for the report)

Currently, when there are vulnerabilities found, we wouldn't show the report, but definitely can show it out too. I'll patch a new flag for this over the weekend when I have time; but feel free to submit a pull request to help out too!

**Comment by jeemok** [comment]
Published `v1.3.0` included this changes
