### ISSUE TITLE
Add an option to remove colors

### ISSUE THREAD

**Issue by jota0222** [jeemok/better-npm-audit#85]
Just a feature request, if it's possible, **could you add an option to remove the ANSI colors of the output?** I would like to save the output to a file without the need of using `sed` command with regular expressions that are not so regular for any OS and the command also is not always available on Windows.

Thanks for your work, this library has been very helpful to me as a Security reviewer.

**Comment by jeemok** [comment]
hi @jota0222 , I've published a new version 3.11.0 that will support the [no-color standard](https://no-color.org/) by setting the environment variable `NO_COLOR` ([Readme](https://github.com/jeemok/better-npm-audit/tree/v3.11.0?tab=readme-ov-file#environment-variables)). Thank you @ericcornelissen for the PR!
