### ISSUE TITLE
production flag in Version 3.8.3 does not work for older npm versions

### ISSUE THREAD

**Issue by gemafrzen** [jeemok/better-npm-audit#98]
Hello, 

the added code in pull request "Use "--omit=dev" internally on newer npm version (#86)" is not correct and the version check is always false. Thus the production flag is not used.

I think the solution is to change the following function
```
function getNpmVersion() {
    var version = child_process_1.exec('npm --version');
    return version.stdout.toString();
}
```
into 
```
function getNpmVersion() {
  var version = child_process_1.execSync('npm --version');
    return version.toString();
}
```

In addition please re-add the test for older versions.

Best regards,
Erik

**Comment by jeemok** [comment]
Released in `3.9.0`. Thank you @ericcornelissen for fixing this!
